//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEP.BusinessLogic.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntityModel : DbContext
    {
        public EntityModel()
            : base("name=EntityModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChooseCorrectQuestion> ChooseCorrectQuestions { get; set; }
        public virtual DbSet<ChooseCorrectVariant> ChooseCorrectVariants { get; set; }
        public virtual DbSet<Lecture> Lectures { get; set; }
        public virtual DbSet<LiteratureItem> LiteratureItems { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<StudentAnswer> StudentAnswers { get; set; }
        public virtual DbSet<StudentExamination> StudentExaminations { get; set; }
        public virtual DbSet<StudentLectureReading> StudentLectureReadings { get; set; }
        public virtual DbSet<StudentModuleReading> StudentModuleReadings { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentSubjectReading> StudentSubjectReadings { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<TestsRelation> TestsRelations { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserSubject> UserSubjects { get; set; }
    }
}
