//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEP.BusinessLogic.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestsRelation
    {
        public int Id { get; set; }
        public int TestId { get; set; }
        public int ModuleId { get; set; }
        public Nullable<int> LectureId { get; set; }
    
        public virtual Lecture Lecture { get; set; }
        public virtual Module Module { get; set; }
        public virtual Test Test { get; set; }
    }
}
